//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrasp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobState> JobStates { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ScraspRole> ScraspRoles { get; set; }
        public virtual DbSet<ScraspUser> ScraspUsers { get; set; }
        public virtual DbSet<Sprint> Sprints { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<StoryState> StoryStates { get; set; }
        public virtual DbSet<StoryType> StoryTypes { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
