//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrasp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int id { get; set; }
        public int Projects_id { get; set; }
        public int ScraspUsers_id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ScraspUser ScraspUser { get; set; }
    }
}
